# Generated by Django 4.2.2 on 2023-07-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='responses',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='subject_from_email',
        ),
    ]
